// api 호출 (여기에 기능별 axios 설정 로직이 들어갈 예정)
// 지금은 더미 데이터를 리턴하는 구조입니다. 나중에 API 연결 시 이 부분만 수정하면 됩니다.

export const productData = async () => {
  return Promise.resolve({
    "정수기": [
      {
        id: 1,
        rank: 1,
        name: "SAYREN 정수기 A",
        model: "WD523VC",
        price: "20,400",
        salePrice: "0",
        img: "/image/image4.png",
      },
      {
        id: 2,
        rank: 2,
        name: "SAYREN 정수기 B",
        model: "WD520AWB",
        price: "14,400",
        salePrice: "0",
        img: "/image/image4.png",
      },
      {
        id: 3,
        rank: 3,
        name: "SAYREN 정수기 C",
        model: "WD520AWB",
        price: "14,400",
        salePrice: "0",
        img: "/image/image4.png",
      },
      {
        id: 4,
        rank: 4,
        name: "SAYREN 정수기 D",
        model: "WD525VC",
        price: "25,000",
        salePrice: "19,000",
        img: "/image/image4.png",
      },
    ],
    "TV": [
      {
        id: 5,
        rank: 1,
        name: "SAYREN 올레드 TV",
        model: "OLED55C2",
        price: "79,000",
        salePrice: "59,000",
        img: "/image/image2.svg",
      },
      {
        id: 6,
        rank: 2,
        name: "SAYREN 올레드 TV",
        model: "OLED55C2",
        price: "79,000",
        salePrice: "59,000",
        img: "/image/image2.svg",
      },
      {
        id: 7,
        rank: 3,
        name: "SAYREN 올레드 TV",
        model: "OLED55C2",
        price: "79,000",
        salePrice: "59,000",
        img: "/image/image2.svg",
      },
      {
        id: 8,
        rank: 4,
        name: "SAYREN 올레드 TV",
        model: "OLED65C2",
        price: "99,000",
        salePrice: "79,000",
        img: "/image/image2.svg",
      },
    ],
    "에어컨": [
      {
        id: 9,
        rank: 1,
        name: "SAYREN 에어컨 A",
        model: "AC9999",
        price: "55,000",
        salePrice: "45,000",
        img: "/image/image2.svg",
      },
      {
        id: 10,
        rank: 2,
        name: "SAYREN 에어컨 B",
        model: "AC8888",
        price: "60,000",
        salePrice: "50,000",
        img: "/image/image2.svg",
      },
      {
        id: 11,
        rank: 3,
        name: "SAYREN 에어컨 C",
        model: "AC7777",
        price: "65,000",
        salePrice: "55,000",
        img: "/image/image2.svg",
      },
      {
        id: 12,
        rank: 4,
        name: "SAYREN 스탠드형 에어컨",
        model: "AC6666",
        price: "70,000",
        salePrice: "60,000",
        img: "/image/image2.svg",
      },
    ],
    "냉장고": [
      {
        id: 13,
        rank: 1,
        name: "SAYREN 냉장고 A",
        model: "REF1234",
        price: "65,000",
        salePrice: "55,000",
        img: "/image/image2.svg",
      },
      {
        id: 14,
        rank: 2,
        name: "SAYREN 냉장고 B",
        model: "REF5678",
        price: "70,000",
        salePrice: "60,000",
        img: "/image/image2.svg",
      },
      {
        id: 15,
        rank: 3,
        name: "SAYREN 냉장고 C",
        model: "REF9012",
        price: "80,000",
        salePrice: "70,000",
        img: "/image/image2.svg",
      },
      {
        id: 16,
        rank: 4,
        name: "SAYREN 양문형 냉장고",
        model: "REF3456",
        price: "90,000",
        salePrice: "80,000",
        img: "/image/image2.svg",
      },
    ],
    "워시타워": [
      {
        id: 17,
        rank: 1,
        name: "SAYREN 워시타워 A",
        model: "WT9999",
        price: "59,900",
        salePrice: "49,900",
        img: "/image/image2.svg",
      },
      {
        id: 18,
        rank: 2,
        name: "SAYREN 워시타워 B",
        model: "WT8888",
        price: "65,000",
        salePrice: "55,000",
        img: "/image/image2.svg",
      },
      {
        id: 19,
        rank: 3,
        name: "SAYREN 워시타워 C",
        model: "WT7777",
        price: "70,000",
        salePrice: "60,000",
        img: "/image/image2.svg",
      },
      {
        id: 20,
        rank: 4,
        name: "SAYREN 워시타워 D",
        model: "WT6666",
        price: "75,000",
        salePrice: "65,000",
        img: "/image/image2.svg",
      },
    ],
    "공기청정기": [
      {
        id: 21,
        rank: 1,
        name: "SAYREN 공기청정기 A",
        model: "AC1234",
        price: "19,900",
        salePrice: "15,900",
        img: "/image/image2.svg",
      },
      {
        id: 22,
        rank: 2,
        name: "SAYREN 공기청정기 B",
        model: "AC5678",
        price: "25,000",
        salePrice: "20,000",
        img: "/image/image2.svg",
      },
      {
        id: 23,
        rank: 3,
        name: "SAYREN 공기청정기 C",
        model: "AC9012",
        price: "30,000",
        salePrice: "25,000",
        img: "/image/image2.svg",
      },
      {
        id: 24,
        rank: 4,
        name: "SAYREN 타워형 공기청정기",
        model: "AC3456",
        price: "35,000",
        salePrice: "30,000",
        img: "/image/image2.svg",
      },
    ],
    "의류건조기": [
      {
        id: 25,
        rank: 1,
        name: "SAYREN 건조기 A",
        model: "DR5678",
        price: "39,900",
        salePrice: "29,900",
        img: "/image/image2.svg",
      },
      {
        id: 26,
        rank: 2,
        name: "SAYREN 건조기 B",
        model: "DR9012",
        price: "45,000",
        salePrice: "35,000",
        img: "/image/image2.svg",
      },
      {
        id: 27,
        rank: 3,
        name: "SAYREN 건조기 C",
        model: "DR3456",
        price: "50,000",
        salePrice: "40,000",
        img: "/image/image2.svg",
      },
      {
        id: 28,
        rank: 4,
        name: "SAYREN 대용량 건조기",
        model: "DR7890",
        price: "55,000",
        salePrice: "45,000",
        img: "/image/image2.svg",
      },
    ],
    "식기세척기": [
      {
        id: 29,
        rank: 1,
        name: "SAYREN 식기세척기 A",
        model: "DW2024",
        price: "35,000",
        salePrice: "29,000",
        img: "/image/image2.svg",
      },
      {
        id: 30,
        rank: 2,
        name: "SAYREN 식기세척기 B",
        model: "DW3035",
        price: "40,000",
        salePrice: "35,000",
        img: "/image/image2.svg",
      },
      {
        id: 31,
        rank: 3,
        name: "SAYREN 식기세척기 C",
        model: "DW4046",
        price: "45,000",
        salePrice: "40,000",
        img: "/image/image2.svg",
      },
      {
        id: 32,
        rank: 4,
        name: "SAYREN 빌트인 식기세척기",
        model: "DWBUILD1",
        price: "50,000",
        salePrice: "45,000",
        img: "/image/image2.svg",
      },
    ],
    "세탁기": [
      {
        id: 33,
        rank: 1,
        name: "SAYREN 세탁기 A",
        model: "WM1234",
        price: "49,000",
        salePrice: "39,000",
        img: "/image/image2.svg",
      },
      {
        id: 34,
        rank: 2,
        name: "SAYREN 세탁기 B",
        model: "WM5678",
        price: "55,000",
        salePrice: "45,000",
        img: "/image/image2.svg",
      },
      {
        id: 35,
        rank: 3,
        name: "SAYREN 세탁기 C",
        model: "WM9012",
        price: "60,000",
        salePrice: "50,000",
        img: "/image/image2.svg",
      },
      {
        id: 36,
        rank: 4,
        name: "SAYREN 드럼 세탁기",
        model: "DRUMWM1",
        price: "70,000",
        salePrice: "60,000",
        img: "/image/image2.svg",
      },
    ],
    "스타일러": [
      {
        id: 37,
        rank: 1,
        name: "SAYREN 스타일러 A",
        model: "ST5678",
        price: "29,900",
        salePrice: "24,900",
        img: "/image/image2.svg",
      },
      {
        id: 38,
        rank: 2,
        name: "SAYREN 스타일러 B",
        model: "ST9012",
        price: "35,000",
        salePrice: "29,000",
        img: "/image/image2.svg",
      },
      {
        id: 39,
        rank: 3,
        name: "SAYREN 스타일러 C",
        model: "ST3456",
        price: "40,000",
        salePrice: "35,000",
        img: "/image/image2.svg",
      },
      {
        id: 40,
        rank: 4,
        name: "SAYREN 5벌 스타일러",
        model: "ST5GARMENT",
        price: "45,000",
        salePrice: "40,000",
        img: "/image/image2.svg",
      },
    ],
  });
};